package com.peyess.salesapp.features.pdf.service_order.html

import com.peyess.salesapp.features.pdf.service_order.model.ServiceOrder
import com.peyess.salesapp.features.pdf.utils.printDate
import com.peyess.salesapp.features.pdf.utils.printDocument
import com.peyess.salesapp.features.pdf.utils.printValue

//<!-- nome_responsavel, cpf_responsavel, data_prescrição  -->
//val conditions = "<tr class=\"row38\"> <td class=\"column0 style38 s style40\" colspan=\"11\">CONDIÇÕES GERAIS</td></tr><tr class=\"row39\"> <td class=\"column0 style53 s style55\" colspan=\"11\"><span style=\"color:#000000; font-family:'Calibri'; font-size:8pt\">Eu,</span><span style=\"font-weight:bold; color:#000000; font-family:'Calibri'; font-size:8pt\"> %s</span><span style=\"color:#000000; font-family:'Calibri'; font-size:8pt\"> inscrito no CPF/MF de nº </span><span style=\"font-weight:bold; color:#000000; font-family:'Calibri'; font-size:8pt\">%s</span><span style=\"color:#000000; font-family:'Calibri'; font-size:8pt\"> ,declaro que apresentei sob a minha responsabilidade a prescrição para fabricação de lentes corretivas de visão, datada de </span><span style=\"font-weight:bold; color:#000000; font-family:'Calibri'; font-size:8pt\">%s</span><span style=\"color:#000000; font-family:'Calibri'; font-size:8pt\">, que deverá ser confeccionada em medidas exatas a minha necessidade. Foi-me aclarado que a confecção das lentes acontece de modo exclusivo, sem possibilidade de reaproveitamento em caso cancelamento do pedido. Assim, autorizo expressamente a fabricação das lentes, tendo ciência que, em caso de rescisão imotivada de minha parte, serão devidos</span><span style=\"font-weight:bold; color:#000000; font-family:'Calibri'; font-size:8pt\"> 30% (trinta por cento)</span><span style=\"color:#000000; font-family:'Calibri'; font-size:8pt\"> do valor pago para ressarcimento das despesas com este cancelamento em favor da</span><span style=\"font-weight:bold; color:#000000; font-family:'Calibri'; font-size:8pt\"> ÓTICAS DINIZ</span><span style=\"color:#000000; font-family:'Calibri'; font-size:8pt\">. Por ser expressão da verdade, para que surtam os efeitos necessários, firmo o presente. </span><span style=\"color:#000000; font-family:'Calibri'; font-size:11pt\"><br/></span></td></tr><tr class=\"row43\"> <td class=\"column0 style36 s style37\" colspan=\"7\">Assinatura:____________________________________________________________________________</td><td class=\"column7 style34 s style35\" colspan=\"4\">( ) Desejo receber promoções e lançamentos via meios eletrônicos</td></tr>"

fun buildConditionsSection(serviceOrder: ServiceOrder): String {
    val payerName = serviceOrder.responsibleName
    val payerDocument = serviceOrder.responsibleDocument

    val prescriptionDate = serviceOrder.prescriptionDate

    return if (serviceOrder.isCopy) {
        "<tr class=\"row38\"> <td class=\"column0 style82 s style84\" colspan=\"11\">CONDIÇÕES GERAIS</td></tr><tr class=\"row39\"> <td class=\"column0 style53 s style55\" colspan=\"11\"><span style=\"color:#000000; font-family:'Calibri'; font-size:8pt\">Eu,</span><span style=\"font-weight:bold; color:#000000; font-family:'Calibri'; font-size:8pt\"> ${printValue(payerName)}</span><span style=\"color:#000000; font-family:'Calibri'; font-size:8pt\"> inscrito(a) no CPF/MF de nº </span><span style=\"font-weight:bold; color:#000000; font-family:'Calibri'; font-size:8pt\">${printDocument(payerDocument)}</span><span style=\"color:#000000; font-family:'Calibri'; font-size:8pt\">, declaro que optei por copiar a prescrição das lentes oftálmicas anteriores para fabricação de novas lentes corretivas de visão sob minha responsabilidade, estando assim ciente que não haverá garantia ou trocas por não adaptação à prescrição utilizada. Foi-me aclarado que a confecção das lentes acontece de modo exclusivo, sem possibilidade de reaproveitamento em caso cancelamento do pedido. Assim, autorizo expressamente a fabricação das lentes, tendo ciência que, em caso de rescisão imotivada de minha parte, serão devidos</span><span style=\"font-weight:bold; color:#000000; font-family:'Calibri'; font-size:8pt\"> 30% (trinta por cento)</span><span style=\"color:#000000; font-family:'Calibri'; font-size:8pt\"> do valor pago para ressarcimento das despesas com este cancelamento em favor da</span><span style=\"font-weight:bold; color:#000000; font-family:'Calibri'; font-size:8pt\"> ÓTICAS DINIZ</span><span style=\"color:#000000; font-family:'Calibri'; font-size:8pt\">. Por ser expressão da verdade, para que surtam os efeitos necessários, firmo o presente. </span><span style=\"color:#000000; font-family:'Calibri'; font-size:11pt\"><br/></span></td></tr><tr class=\"row43\"> <td class=\"column0 style36 s style37\" colspan=\"7\">Assinatura:____________________________________________________________________________</td><td class=\"column7 style34 s style35\" colspan=\"4\">( ) Desejo receber promoções e lançamentos via meios eletrônicos</td></tr>"
    } else {
        "<tr class=\"row38\"> <td class=\"column0 style82 s style84\" colspan=\"11\">CONDIÇÕES GERAIS</td></tr><tr class=\"row39\"> <td class=\"column0 style53 s style55\" colspan=\"11\"><span style=\"color:#000000; font-family:'Calibri'; font-size:8pt\">Eu,</span><span style=\"font-weight:bold; color:#000000; font-family:'Calibri'; font-size:8pt\"> ${printValue(payerName)}</span><span style=\"color:#000000; font-family:'Calibri'; font-size:8pt\"> inscrito(a) no CPF/MF de nº </span><span style=\"font-weight:bold; color:#000000; font-family:'Calibri'; font-size:8pt\">${printDocument(payerDocument)}</span><span style=\"color:#000000; font-family:'Calibri'; font-size:8pt\">, declaro que apresentei sob a minha responsabilidade a prescrição para fabricação de lentes corretivas de visão, datada de </span><span style=\"font-weight:bold; color:#000000; font-family:'Calibri'; font-size:8pt\">${printDate(prescriptionDate)}</span><span style=\"color:#000000; font-family:'Calibri'; font-size:8pt\">, que deverá ser confeccionada em medidas exatas a minha necessidade. Foi-me aclarado que a confecção das lentes acontece de modo exclusivo, sem possibilidade de reaproveitamento em caso cancelamento do pedido. Assim, autorizo expressamente a fabricação das lentes, tendo ciência que, em caso de rescisão imotivada de minha parte, serão devidos</span><span style=\"font-weight:bold; color:#000000; font-family:'Calibri'; font-size:8pt\"> 30% (trinta por cento)</span><span style=\"color:#000000; font-family:'Calibri'; font-size:8pt\"> do valor pago para ressarcimento das despesas com este cancelamento em favor da</span><span style=\"font-weight:bold; color:#000000; font-family:'Calibri'; font-size:8pt\"> ÓTICAS DINIZ</span><span style=\"color:#000000; font-family:'Calibri'; font-size:8pt\">. Por ser expressão da verdade, para que surtam os efeitos necessários, firmo o presente. </span><span style=\"color:#000000; font-family:'Calibri'; font-size:11pt\"><br/></span></td></tr><tr class=\"row43\"> <td class=\"column0 style36 s style37\" colspan=\"7\">Assinatura:____________________________________________________________________________</td><td class=\"column7 style34 s style35\" colspan=\"4\">( ) Desejo receber promoções e lançamentos via meios eletrônicos</td></tr>"
    }
}